# Run clang-format and EditorConfig check in parallel

name: cpp-format-check

on: [pull_request, workflow_dispatch]

jobs:
  clang_format_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: clang-format check
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: .
          exclude: build out
          extensions: c,cpp,cc,cxx,h,hpp,hh,hxx,tpp,inl
          clangFormatVersion: 13

  editor_config_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: EditorConfig check
        uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
